Debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,9 +61,12 @@ jobs:
           index-digest-version: ${{ matrix.index-digest-version }}
           index-digest-dsn: ${{ env.WRONG_MYSQL_DSN }}
 
+      - run: |
+          echo "Step context: ${{ toJSON(steps.action-run-wrong-dsn) }}"
+
       # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context
-      - if: steps.action-run-wrong-dsn.outcome != "failure"
-        run: exit 1
+#       - if: steps.action-run-wrong-dsn.outcome != "failure"
+#         run: exit 1
 
 
       #
